#!/usr/bin/env python3
"""gen_dsdata.py TENNIS.EXE > src/dsdata.c
Dumps the initialised data segment of the original executable (constant tables, strings) plus its pointer
relocations, so the rewrite does not need TENNIS.EXE at run time."""
import struct, sys

d = open(sys.argv[1], 'rb').read()
ne = struct.unpack_from('<I', d, 0x3c)[0]
assert d[ne:ne+2] == b'NE'
nseg, = struct.unpack_from('<H', d, ne + 0x1c)
segtb = ne + struct.unpack_from('<H', d, ne + 0x22)[0]
shift, = struct.unpack_from('<H', d, ne + 0x32)
autods, = struct.unpack_from('<H', d, ne + 0x0e)
off, sz = struct.unpack_from('<HH', d, segtb + (autods - 1) * 8)
off <<= shift
data = d[off:off + sz]
nrel, = struct.unpack_from('<H', d, off + sz)
rel = {}
for i in range(nrel):
    at, rt, o, t1, t2 = struct.unpack_from('<BBHHH', d, off + sz + 2 + i * 8)
    if (rt & 3) == 0 and t1 == autods and at in (3, 5):
        rel[o] = t2

print('/* Generated by tools/gen_dsdata.py - initialised data segment of the original program */')
print('#include <stdint.h>')
print('const unsigned ds_image_size = %d;' % len(data))
print('const uint8_t ds_image[%d] = {' % len(data))
for i in range(0, len(data), 24):
    print('    ' + ','.join('%d' % b for b in data[i:i+24]) + ',')
print('};')
print('const unsigned ds_reloc_count = %d;' % len(rel))
print('const uint16_t ds_reloc[][2] = {')
for o, t in sorted(rel.items()):
    print('    {0x%x, 0x%x},' % (o, t))
print('};')
